#!/usr/bin/env bash
# Regenerates src/bindings.rs from the QNN (QAIRT/AI Engine Direct) C headers.
# The generated file is committed so the crate builds without the proprietary SDK.
# Only Qualcomm's headers are read; no QNN binaries are vendored into the repo.
#
# Usage:
#   QNN_SDK_ROOT=/path/to/qairt/2.xx.xx.xxxxxx ./scripts/regen-bindings.sh
#
# Requires: bindgen-cli (`cargo install bindgen-cli`) and libclang.
set -euo pipefail

: "${QNN_SDK_ROOT:?set QNN_SDK_ROOT to an extracted qairt/<version> dir}"
INC="$QNN_SDK_ROOT/include/QNN"
[ -d "$INC" ] || { echo "no include/QNN under $QNN_SDK_ROOT" >&2; exit 1; }

HERE="$(cd "$(dirname "$0")/.." && pwd)"

bindgen "$HERE/wrapper.h" -o "$HERE/src/bindings.rs" \
  --allowlist-type '(Qnn|QNN).*' \
  --allowlist-function '(Qnn|QNN).*' \
  --allowlist-var '(Qnn|QNN).*' \
  --default-enum-style newtype \
  --no-layout-tests \
  --no-doc-comments \
  --merge-extern-blocks \
  --raw-line '// @generated by scripts/regen-bindings.sh from Qualcomm QNN headers. Do not edit.' \
  -- -I"$INC"

echo "wrote $HERE/src/bindings.rs from $INC"
